# Generated by Django 2.2.27 on 2022-03-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'permissions': (('add_department', '允许添加部门'), ('view_department', '允许查看部门'), ('change_department', '允许修改部门'), ('delete_department', '允许删除部门')),
                'default_permissions': (),
            },
        ),
    ]
