# Generated by Django 2.2.24 on 2021-11-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0004_auto_20210918_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionmeta',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_metas', to='river.Workflow', verbose_name='Workflow'),
        ),
    ]
