# Generated by Django 2.2.24 on 2022-02-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0007_auto_20220120_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_approval_metas', to='river.Workflow', verbose_name='Workflow'),
        ),
    ]
