version: '3'

services:
  dj:
    build: .
    command: waitress-serve --listen=0.0.0.0:8000 proj.wsgi:application
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11
    # restart: always
    ports:
      - "52345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
  # adminer:
  #   image: adminer
  #   ports:
  #     - 58080:8080

volumes:
  postgres_data:

