# Generated by Django 2.2.28 on 2022-05-23 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=files.utils.file_generate_upload_path, verbose_name='文件')),
                ('original_file_name', models.TextField(verbose_name='原文件名')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='文件名称')),
                ('file_type', models.CharField(max_length=255, verbose_name='文件类型')),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
        ),
    ]
