# Generated by Django 4.2.14 on 2024-08-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
