# Generated by Django 2.2.27 on 2022-03-29 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0010_auto_20220325_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='单据编号')),
                ('order_date', models.DateField(verbose_name='单据日期')),
                ('prefix', models.CharField(max_length=8, verbose_name='单号前缀')),
                ('number', models.PositiveIntegerField(verbose_name='单据号数')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', max_length=1024, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State', verbose_name='流转状态')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'permissions': (('add_ticket', '允许添加工单'), ('view_ticket', '允许查看工单'), ('change_ticket', '允许修改工单'), ('delete_ticket', '允许删除工单'), ('import_ticket', '允许导入工单'), ('export_ticket', '允许导出工单'), ('submit_ticket', '允许提交工单'), ('resolve_ticket', '允许处理工单')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AllTicket',
            fields=[
            ],
            options={
                'verbose_name': '所有工单',
                'verbose_name_plural': '所有工单',
                'permissions': (('view_allticket', '允许查看所有工单'), ('export_allticket', '允许导出所有工单')),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('ticket.ticket',),
        ),
        migrations.CreateModel(
            name='MyTicket',
            fields=[
            ],
            options={
                'verbose_name': '我的工单',
                'verbose_name_plural': '我的工单',
                'permissions': (('add_myticket', '允许添加我的工单'), ('view_myticket', '允许查看我的工单'), ('change_myticket', '允许修改我的工单'), ('delete_myticket', '允许删除我的工单'), ('import_myticket', '允许导入我的工单'), ('export_myticket', '允许导出我的工单')),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('ticket.ticket',),
        ),
        migrations.CreateModel(
            name='PendingTicket',
            fields=[
            ],
            options={
                'verbose_name': '待处理的工单',
                'verbose_name_plural': '待处理的工单',
                'permissions': (('view_pendingticket', '允许查看待处理的工单'), ('export_pendingticket', '允许导出待处理的工单')),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('ticket.ticket',),
        ),
        migrations.CreateModel(
            name='ProcessedTicket',
            fields=[
            ],
            options={
                'verbose_name': '已处理的工单',
                'verbose_name_plural': '已处理的工单',
                'permissions': (('view_processedticket', '允许查看已处理的工单'), ('export_processedticket', '允许导出已处理的工单')),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('ticket.ticket',),
        ),
    ]
