# Generated by Django 2.2.27 on 2022-03-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTicket',
            fields=[
            ],
            options={
                'verbose_name': '待处理的工单',
                'verbose_name_plural': '待处理的工单',
                'permissions': (('add_pendingticket', '允许添加待处理的工单'), ('view_pendingticket', '允许查看待处理的工单'), ('change_pendingticket', '允许修改待处理的工单'), ('delete_pendingticket', '允许删除待处理的工单'), ('import_pendingticket', '允许导入待处理的工单'), ('export_pendingticket', '允许导出待处理的工单')),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('ticket.ticket',),
        ),
        migrations.CreateModel(
            name='ProcessedTicket',
            fields=[
            ],
            options={
                'verbose_name': '已处理的工单',
                'verbose_name_plural': '已处理的工单',
                'permissions': (('add_processedticket', '允许添加已处理的工单'), ('view_processedticket', '允许查看已处理的工单'), ('change_processedticket', '允许修改已处理的工单'), ('delete_processedticket', '允许删除已处理的工单'), ('import_processedticket', '允许导入已处理的工单'), ('export_processedticket', '允许导出已处理的工单')),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('ticket.ticket',),
        ),
    ]
