# Generated by Django 2.2.27 on 2022-03-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_pendingticket_processedticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTicket',
            fields=[
            ],
            options={
                'verbose_name': '所有工单',
                'verbose_name_plural': '所有工单',
                'permissions': (('add_allticket', '允许添加所有工单'), ('view_allticket', '允许查看所有工单'), ('change_allticket', '允许修改所有工单'), ('delete_allticket', '允许删除所有工单'), ('import_allticket', '允许导入所有工单'), ('export_allticket', '允许导出所有工单')),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('ticket.ticket',),
        ),
    ]
