# Generated by Django 2.2.27 on 2022-03-29 03:42

from django.db import migrations
from django.utils import timezone


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Ticket = apps.get_model('ticket', 'Ticket')
    Ticket.objects.using(db_alias).update(
        created_at=timezone.now(),
        updated_at=timezone.now(),
    )


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Ticket = apps.get_model('ticket', 'Ticket')
    Ticket.objects.using(db_alias).update(created_at=None, updated_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20220329_1141'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
