# Generated by Django 2.2.16 on 2022-06-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('phone', models.CharField(max_length=255, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='删除时间')),
                ('order_date', models.DateField(verbose_name='订单日期')),
            ],
            options={
                'verbose_name': '订单模板',
                'verbose_name_plural': '订单模板',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='单价')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ordertemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.OrderTemplate')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='总金额')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
            bases=('testapp.ordertemplate',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='删除时间')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='总价')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='testapp.Product', verbose_name='产品')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='testapp.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
    ]
