# Generated by Django 2.2.28 on 2022-09-29 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updater', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': 'Testapp',
                'verbose_name_plural': 'Testapp',
                'permissions': (('add_testapp', '允许添加Testapp'), ('view_testapp', '允许查看Testapp'), ('change_testapp', '允许修改Testapp'), ('delete_testapp', '允许删除Testapp'), ('import_testapp', '允许导入Testapp'), ('export_testapp', '允许导出Testapp')),
                'default_permissions': (),
            },
        ),
    ]
