# Generated by Django 2.2.28 on 2022-04-16 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='订单日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'permissions': (('add_order', '允许添加订单'), ('view_order', '允许查看订单'), ('change_order', '允许修改订单'), ('delete_order', '允许删除订单'), ('import_order', '允许导入订单'), ('export_order', '允许导出订单')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='单价')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='数量')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'permissions': (('add_item', '允许添加订单明细'), ('view_item', '允许查看订单明细'), ('change_item', '允许修改订单明细'), ('delete_item', '允许删除订单明细'), ('import_item', '允许导入订单明细'), ('export_item', '允许导出订单明细')),
                'default_permissions': (),
            },
        ),
    ]
