FROM python:3.10-slim


# 清空所有现有的源列表，并添加清华大学源
RUN echo '' > /etc/apt/sources.list && \
    rm -rf /etc/apt/sources.list.d/* && \
    echo 'deb http://mirrors.tuna.tsinghua.edu.cn/debian/ stable main contrib non-free' > /etc/apt/sources.list && \
    echo 'deb http://mirrors.tuna.tsinghua.edu.cn/debian/ stable-updates main contrib non-free' >> /etc/apt/sources.list

# 设置环境变量
ENV LANG=en_US.UTF-8 LC_ALL=en_US.utf8
# 设置时区，否则存入到数据库的时间会不正确
RUN ln -s -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone

# 阻止 Python 生成.pyc文件、阻止段错误上启用 Python 回溯
ENV PYTHONPATH=${PYTHONPATH}:${PWD} PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONFAULTHANDLER=1

WORKDIR /code
RUN chown -R 1001:0 /code
# USER 1001

# Copy local code to the container image.
COPY . .

RUN apt-get update -y && apt-get install -y python3-dev default-libmysqlclient-dev build-essential pkg-config
RUN pip3 install poetry==1.5.1 -i https://mirrors.aliyun.com/pypi/simple/
RUN poetry config virtualenvs.create false && poetry install --only main

# 收集静态文件
RUN poetry run python manage.py collectstatic
CMD poetry run gunicorn -b 0.0.0.0:8000 -w 1 config.wsgi:application
