# Generated by Django 2.2.27 on 2022-02-28 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='App Token')),
                ('name', models.CharField(max_length=128, verbose_name='第三方应用名称')),
                ('memo', models.TextField(blank=True, default='', max_length=4096, verbose_name='备注')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='apptokens', to=settings.AUTH_USER_MODEL, verbose_name='所属帐号')),
            ],
            options={
                'verbose_name': 'App Token',
                'verbose_name_plural': 'App Token',
                'permissions': (('add_apptoken', '允许添加App Token'), ('view_apptoken', '允许查看App Token'), ('change_apptoken', '允许修改App Token'), ('delete_apptoken', '允许删除App Token')),
                'default_permissions': (),
            },
        ),
    ]
