# Generated by Django 2.2.28 on 2022-05-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_type', models.CharField(choices=[('upload', '上传'), ('download', '下载')], max_length=16, verbose_name='操作类型')),
                ('md5', models.CharField(default='', max_length=128, verbose_name='MD5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operater', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '数据同步历史',
                'verbose_name_plural': '数据同步历史',
                'permissions': (('add_emailsynclog', '允许添加数据同步历史'), ('view_emailsynclog', '允许查看数据同步历史'), ('change_emailsynclog', '允许修改数据同步历史'), ('delete_emailsynclog', '允许删除数据同步历史'), ('import_emailsynclog', '允许导入数据同步历史'), ('export_emailsynclog', '允许导出数据同步历史')),
                'default_permissions': (),
            },
        ),
    ]
