# Generated by Django 2.2.28 on 2022-05-01 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自定义模型',
                'verbose_name_plural': '自定义模型',
                'permissions': (('add_custommodel', '允许添加自定义模型'), ('view_custommodel', '允许查看自定义模型'), ('change_custommodel', '允许修改自定义模型'), ('delete_custommodel', '允许删除自定义模型')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmailSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_at', models.DateTimeField(auto_now_add=True, verbose_name='同步时间')),
                ('md5', models.CharField(default='', max_length=128, verbose_name='MD5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sync_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='同步人')),
            ],
            options={
                'verbose_name': '邮件同步历史',
                'verbose_name_plural': '邮件同步历史',
                'permissions': (('add_emailsynclog', '允许添加邮件同步历史'), ('view_emailsynclog', '允许查看邮件同步历史'), ('change_emailsynclog', '允许修改邮件同步历史'), ('delete_emailsynclog', '允许删除邮件同步历史'), ('import_emailsynclog', '允许导入邮件同步历史'), ('export_emailsynclog', '允许导出邮件同步历史')),
                'default_permissions': (),
            },
        ),
    ]
