[tool.poetry]
name = "230-django-htmx-demo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "230_django_htmx_demo"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.7"
django-htmx = "^1.18.0"
faker = "^26.0.0"


[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
