# Generated by Django 2.2.24 on 2021-08-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20210820_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapproval',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_approvals', to='river.Transition', verbose_name='Transition'),
        ),
    ]
