# Generated by Django 2.2.24 on 2021-12-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0005_auto_20211117_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='onapprovedhook',
            name='is_raise_exception',
            field=models.BooleanField(default=False, verbose_name='是否抛出异常'),
        ),
        migrations.AddField(
            model_name='oncompletehook',
            name='is_raise_exception',
            field=models.BooleanField(default=False, verbose_name='是否抛出异常'),
        ),
        migrations.AddField(
            model_name='ontransithook',
            name='is_raise_exception',
            field=models.BooleanField(default=False, verbose_name='是否抛出异常'),
        ),
    ]
