# Generated by Django 2.2.24 on 2022-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0006_auto_20211214_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapproval',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='transitionapprovalmeta',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='名称'),
        ),
    ]
