# Generated by Django 2.2.27 on 2022-03-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0009_auto_20220221_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapproval',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='批注'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='名称'),
        ),
    ]
