# Generated by Django 2.2.27 on 2022-02-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='编码')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='名称')),
                ('is_locked', models.BooleanField(default=False, verbose_name='锁定')),
                ('in_use', models.BooleanField(default=False, verbose_name='使用中')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'permissions': (('add_datadict', '允许添加数据字典'), ('view_datadict', '允许查看数据字典'), ('change_datadict', '允许修改数据字典'), ('delete_datadict', '允许删除数据字典'), ('import_datadict', '允许导入数据字典'), ('export_datadict', '允许导出数据字典')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DataDictItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='编码')),
                ('label', models.CharField(blank=True, default='', max_length=128, verbose_name='标签')),
                ('master', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='datadict.DataDict', verbose_name='数据字典')),
            ],
            options={
                'verbose_name': '字典明细',
                'verbose_name_plural': '字典明细',
                'permissions': (('add_dictdataitem', '允许添加字典明细'), ('view_dictdataitem', '允许查看字典明细'), ('change_dictdataitem', '允许修改字典明细'), ('delete_dictdataitem', '允许删除字典明细'), ('import_dictdataitem', '允许导入字典明细'), ('export_dictdataitem', '允许导出字典明细')),
                'default_permissions': (),
            },
        ),
    ]
