# Generated by Django 2.2.24 on 2022-02-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0008_auto_20220221_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onapprovedhook',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='river_onapprovedhook_hooks', to='river.Workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='oncompletehook',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='river_oncompletehook_hooks', to='river.Workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='ontransithook',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='river_ontransithook_hooks', to='river.Workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='river.TransitionMeta', verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='river.Workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_approvals', to='river.Workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='transitionapprovalmeta',
            name='transition_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_approval_meta', to='river.TransitionMeta', verbose_name='Transition Meta'),
        ),
    ]
