# Generated by Django 2.2.28 on 2022-10-09 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('river', '0002_auto_20221009_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='工单号')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', max_length=1024, verbose_name='详情')),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State', verbose_name='状态')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'permissions': (('add_ticket', '允许添加工单'), ('view_ticket', '允许查看工单'), ('change_ticket', '允许修改工单'), ('delete_ticket', '允许删除工单'), ('import_ticket', '允许导入工单'), ('export_ticket', '允许导出工单'), ('open_ticket', '允许提交工单'), ('resovle_ticket', '允许处理工单')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MyTicket',
            fields=[
            ],
            options={
                'verbose_name': '我的工单',
                'verbose_name_plural': '我的工单',
                'permissions': (('add_myticket', '允许添加我的工单'), ('view_myticket', '允许查看我的工单'), ('change_myticket', '允许修改我的工单'), ('delete_myticket', '允许删除我的工单'), ('import_myticket', '允许导入我的工单'), ('export_myticket', '允许导出我的工单')),
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('ticket.ticket',),
        ),
    ]
